// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGjDK-QOQWE3voZtH4fEMu5_wVTnutV_g',
    appId: '1:11309361150:web:6393fa3d48289e507342af',
    messagingSenderId: '11309361150',
    projectId: 'linktreemanager-a2c7d',
    authDomain: 'linktreemanager-a2c7d.firebaseapp.com',
    storageBucket: 'linktreemanager-a2c7d.appspot.com',
    measurementId: 'G-39SBTDZXZ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjKXi1CE9J1gWqZ3cP-kQqqElQf0L3H3I',
    appId: '1:11309361150:android:80711e967bf7ceac7342af',
    messagingSenderId: '11309361150',
    projectId: 'linktreemanager-a2c7d',
    storageBucket: 'linktreemanager-a2c7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnrmiWKLeaf2CS-lMUJ_npTPV4VF1_HQM',
    appId: '1:11309361150:ios:da938b715fe4aa337342af',
    messagingSenderId: '11309361150',
    projectId: 'linktreemanager-a2c7d',
    storageBucket: 'linktreemanager-a2c7d.appspot.com',
    iosClientId: '11309361150-eealmfjocrc4ngokio4ujf3hqtok5j45.apps.googleusercontent.com',
    iosBundleId: 'com.example.linktreeManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnrmiWKLeaf2CS-lMUJ_npTPV4VF1_HQM',
    appId: '1:11309361150:ios:f65eb67209bba3d57342af',
    messagingSenderId: '11309361150',
    projectId: 'linktreemanager-a2c7d',
    storageBucket: 'linktreemanager-a2c7d.appspot.com',
    iosClientId: '11309361150-o78b2rfqnhjd907nq293ag31q94i64ak.apps.googleusercontent.com',
    iosBundleId: 'com.example.linktreeManager.RunnerTests',
  );
}
