// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAyPEown5_wvF2vcPJqVCiy6oRrK1_0k8',
    appId: '1:998935281684:web:c8a3c61b817c76f50ea701',
    messagingSenderId: '998935281684',
    projectId: 'linktree-66f43',
    authDomain: 'linktree-66f43.firebaseapp.com',
    storageBucket: 'linktree-66f43.appspot.com',
    measurementId: 'G-LG99L1LBHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVAb3_cgiFbR6b-N9Sd1B7YijPYyqL-wE',
    appId: '1:998935281684:android:9ee44a6aad60d7020ea701',
    messagingSenderId: '998935281684',
    projectId: 'linktree-66f43',
    storageBucket: 'linktree-66f43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVwZ2EOmF08SctvbDA52cv81yF7mZiqaU',
    appId: '1:998935281684:ios:2c584113f1309d910ea701',
    messagingSenderId: '998935281684',
    projectId: 'linktree-66f43',
    storageBucket: 'linktree-66f43.appspot.com',
    iosBundleId: 'com.example.linktreeManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVwZ2EOmF08SctvbDA52cv81yF7mZiqaU',
    appId: '1:998935281684:ios:d5604f1c8022e4870ea701',
    messagingSenderId: '998935281684',
    projectId: 'linktree-66f43',
    storageBucket: 'linktree-66f43.appspot.com',
    iosBundleId: 'com.example.linktreeManager.RunnerTests',
  );
}
